version: '3.8'

services:
  app:
    image: mini-baheth:latest
    container_name: mini-baheth
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${API_PORT:-5000}:${API_PORT:-5000}"
    volumes:
      - ./:/code/app
      - ./data:/code/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - API_HOST=0.0.0.0
      - API_PORT=${API_PORT:-5000}
      - API_WORKERS=${API_WORKERS:-4}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost 127.0.0.1 [::1]}
    restart: unless-stopped
