services:
  app:
    image: mini-baheth:latest
    container_name: mini-baheth
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${GRANIAN_PORT:-5000}:${GRANIAN_PORT:-5000}"
    volumes:
      - ./:/code/app
      - ./data:/code/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GRANIAN_HOST=${GRANIAN_HOST:-0.0.0.0}
      - GRANIAN_PORT=${GRANIAN_PORT:-5000}
      - GRANIAN_WORKERS=${GRANIAN_WORKERS:-2}
      - GRANIAN_THREADS=${GRANIAN_THREADS:-1}
      - GRANIAN_INTERFACE=${GRANIAN_INTERFACE:-asginl}
      - GRANIAN_RELOAD=${GRANIAN_RELOAD:-false}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost 127.0.0.1 [::1]}
    restart: unless-stopped
